# Generated by Django 3.1 on 2020-08-28 16:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_auto_20200828_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.CharField(default="kjfdlsaje2edoi23euikjwe", max_length=48),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
